### ISSUE TITLE
End time cannot be before start time

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#110]
Cannot allow `add event Tutorial from today 5pm to today 2pm`.

Should throw back to disambiguation, with a specific error message.

**Comment by louietyj** [comment]
Should be a simple validate() that should be caught by the Model and propagated back to the Controller right?

That was initially part of my ActiveRecordLibrary that was scraped, so we need to find another consistent way to do this sigh.

**Comment by irvinlim** [comment]
What's wrong with doing it in the Event model? I think it should be fine if we throw exceptions and handle them in the controller.

**Comment by louietyj** [comment]
Because validate() is not a Model interface specification, so now everyone will need to write validations and actually catch the validations.

**Comment by louietyj** [comment]
Unless you're suggesting that only Event has the validate() method?

**Comment by irvinlim** [comment]
Oh, nope I meant every model has validation but we can just leave validation for other models as blank for now lor, haha.

Otherwise, we can just do validation within the controller, and just heck it if you want

**Comment by louietyj** [comment]
Sigh...

```
@Override
public boolean validate() {
    return true;
}
```

Not sure what Damith will say.

**Comment by irvinlim** [comment]
We'll fix it... One day
