### ISSUE TITLE
Default date/time for task/event when not specified

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#112]
For tasks, it doesn't really make sense to add the task to be due by the time now on the date specified, but rather either set the time to `00:00` or `23:59`. I think that `00:00` is better.

**For events:**
- [x] Where only 1 date/time is specified, we throw this back to the user to disambiguate. See #111 
- [x] Where 2 dates + 0 times are specified, we should default to start at `00:00` and end at `23:59`.
- [x] Where 0 dates + 2 times are specified, we should default to today's date
- [x] Where only 1 date + 2 times are specified, we should use the same date for both. e.g. `add event Tutorial from tuesday 2pm to 3pm`.
- [x] Where 2 dates + 1 time are specified, we should use the same time for both.

**Comment by louietyj** [comment]
I'm not entirely sure we are even able to tell if the user only specified the date or date + time or time. Natty isn't the most flexible library out there, and the docs are horribly sparse.

**Comment by irvinlim** [comment]
Oh hmm, then how are you setting default values for the time when no time is specified? Or is Natty doing it?

**Comment by louietyj** [comment]
Both date and time empty should be null unless yaocong did something I'm not aware of.

Date without time magically gets a time from Natty.

**Comment by ChaseTiong** [comment]
I didn't touch add controller ><, 
but from Natty, if `add 123 by today` it is going to parse back today date with the current time that it is been parsed.

**Comment by louietyj** [comment]
@irvinlim Can we close this? I don't think we have a nice way to solve this problem.

**Comment by irvinlim** [comment]
Alright, since we can't change Natty's behavior, I think it's acceptable to close.

**Comment by louietyj** [comment]
Can always do it the Yichen way and fork Natty's source, but let's not go there 😂
