### ISSUE TITLE
Bug with list complete/incomplete

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#113]
The behaviour for `list complete` vs `list task complete` is different - I'm seeing events in `list complete`.

We should make both of them behave the same way.

**Comment by ChaseTiong** [comment]
isn't `list complete` is to list all completed **events and tasks**?
while `list task complete` or `list complete task` only list **task** that are complete?

**Comment by louietyj** [comment]
How does one complete an event?

complete/incomplete is different from past/future.

**Comment by ChaseTiong** [comment]
i wrote it in the way to detect the current time too. So as long the event end date is before the current time, it will be considered `complete`

**Comment by ChaseTiong** [comment]
Or you guys want it to be `list complete` will auto recognise as `list task complete` and all events will be ignored

**Comment by irvinlim** [comment]
I think `list complete` makes sense that you'll only be looking for completed tasks, if you want to do it for events maybe `list event over` and `list event ongoing`.

**Comment by ChaseTiong** [comment]
@irvinlim okay, i have make the edit and is in pr :)

**Comment by ChaseTiong** [comment]
Do you guys want the `list event over` and `list event ongoing` ?

**Comment by irvinlim** [comment]
It makes sense to me.

**Comment by louietyj** [comment]
Can we use more generic words for over/ongoing that make sense for tasks too? Because both tasks and events can be filtered by date, we would like words that naturally sound ok for both. On the other hand only tasks can be completed/incomplete.

**Comment by louietyj** [comment]
past/future sounds very forced though, needa find better words

**Comment by ChaseTiong** [comment]
`list prior` and `list scheduled` ?

**Comment by irvinlim** [comment]
I think there's nothing wrong with having separate set of words for both, so `complete` and `incomplete` automatically refer to tasks, while `over` and `ongoing` automatically refer to events?

Can't find any good words..

**Comment by ChaseTiong** [comment]
Okay I have updated it to support `list over` and `list ongoing` , it should only display for events and `list complete` and `list incomplete`, display only tasks.

if you try `list task over` --> it will throw an error. Applies for `list event complete`
with #120
