### ISSUE TITLE
Decide on what to do for inputConfidence

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#114]
I think this has been dragging on long enough already... We have two options:
- Scrap the non-binary implementation of `inputConfidence`, only match exact command keywords (nothing wrong here)
- Spend a long time giving arbitrary weights to tokens that we find in the command and sacrifice our grades for CS3216

:(

**Comment by louietyj** [comment]
You're more keen on leaving the binary implementation huh

**Comment by irvinlim** [comment]
What do you think

**Comment by louietyj** [comment]
I think you tank this project already. Our pivot schema is 2x the size of nusocial D:

Three-way association tables ftw.

**Comment by louietyj** [comment]
ARGHHHHH OPWEIRAOWEIMGADJF

**Comment by irvinlim** [comment]
Cannot la sia

**Comment by louietyj** [comment]
I think we can do a thoroughly shitty version of (2) that serves no real purpose other than allow us to give some flashy examples in our dev guide?

**Comment by louietyj** [comment]
So something that has lots of code but is very marginally better than `startswith("add") ? 1 : 0`

**Comment by irvinlim** [comment]
I don't think that's a good idea, I would go with the simplest solution since the more complicated one is only marginally better. I mean there's still a chance that the user might not have expected his invalid command to be parsed correctly, so we might be overdoing it.

I would go with just declaring a List of `commandWords` for each Controller.

**Comment by louietyj** [comment]
Yeap, hence I'm suggesting that we do a "very simple" complicated one that is just enough to show during demo that we support partially ambiguous commands (:

But sure, we can just fallback to the list of command words.

**Comment by irvinlim** [comment]
Hahaha what is very simple complicated?? I'm just doing what's best since both our projects pivoted 100x and we dont have the time :sob:

**Comment by louietyj** [comment]
addcontroller returns 0.5 if it sees any of the time tokens.

Then we can support `buy milk by 10pm` and hope that no one stress-tests this.

**Comment by louietyj** [comment]
But I agree real-usage wise it's not gonna do anything and could even make things worse, so if you're not keen on doing some crap to show some specific natural commands during demo we can just scrape this.
