### ISSUE TITLE
Searching should not be dual-sided wildcard by default

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#115]
Sorry didn't catch this earlier.

We shouldn't allow dual-sided wildcards, i.e. `%SEARCH_TERM%` in MySQL or `*search_term*`, since it's highly unlikely i want to find stuff like `Complete Assignment 3` when I search for `sign`.

Instead, search results should follow `SEARCH_TERM%`.

**Comment by louietyj** [comment]
Actually SEARCH_TERM% will only match the start of the whole string. I think you want to match the start of a word, not the whole string right?

Should be a simple regex.

**Comment by ChaseTiong** [comment]
okay, will update this. To search with search_term%

**Comment by irvinlim** [comment]
Ah, yeah I mean that la haha it should be intuitive enough

**Comment by ChaseTiong** [comment]
with 
`complete assignment 3`
`sign document`
`test sign`

`find sig` will only return `sign document` , am i right?

**Comment by irvinlim** [comment]
Nope, return `test sign` as well, search individual words, but don't search within the word.

**Comment by ChaseTiong** [comment]
if it is `testsign` , it will not return right?

**Comment by irvinlim** [comment]
Correct.
