### ISSUE TITLE
Find with filter is messy

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#116]
If we allow users to filter their search results using `event` or `complete` keywords for example without allowing flexible ordering (as is the current situation), then it may get messy if they mix up the order.

We can either have flags like `/event`, `/e` or `--event` (but Damith doesn't like UNIX-style commands, so) to denote filters, and treat all non-flags as search terms.

**Comment by louietyj** [comment]
I think this may be one of the rare cases that we can justify comma separation. This would make for more intuitive input anyway.

`list tasks, uncompleted, after christmas, before chinese new year, tag project`

Without commas Tokenizer may also be able to do it actually, so let's see how it goes.

**Comment by irvinlim** [comment]
Oh, I actually was referring to the `find` command where it's allowed to add certain flags. I'm not entirely sure if we should allow filtering at both the `list` and `find` controllers, if so it's better to just combine them.

And I don't really think commas are that intuitive, hmm...

**Comment by louietyj** [comment]
I don't think `find` should even be a separate controller. Dunno who OTOT do one.

`find` is just a specific case of `list` right? list by name.

**Comment by irvinlim** [comment]
So we should combine both into `list`, and allow `list` to accept search terms?

**Comment by louietyj** [comment]
I think it should have naturally been a part of `list` to begin with. We can alias `find` -> `list` if really want, but honestly no point.

**Comment by ChaseTiong** [comment]
I was thinking as list is just listing by status and date and find is by all the keyword he can think of (is the must have features)

**Comment by ChaseTiong** [comment]
@irvinlim actually it is support flexible command, why is it not for the current situation?

**Comment by irvinlim** [comment]
I get different results with `find event a` and `find a event`, not sure if that's supposed to happen?

**Comment by ChaseTiong** [comment]
If search for name behind other keyword, need to include `name`
so try `find event name a` instead of `find event a` (this will be actually be finding event with name "" --> will think of a way to update it to throw error)

**Comment by irvinlim** [comment]
Fixed with #170
