### ISSUE TITLE
UpdateController to accept subset of parameters

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#118]
We need to make `update` accept a subset of parameters, such as only updating name or only updating time.

**Comment by irvinlim** [comment]
One idea would be to namespace the command, like `update name` and `update time`/`update date`.

**Comment by ChaseTiong** [comment]
untag myself and tag @louietyj since it is been merged into master

**Comment by irvinlim** [comment]
Fixed with #141, see #151 for remaining task
