### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by ysqty** [CS2103AUG2016-F11-C1/main#122]
# Developer Guide
- Should the related components be in the same colour? The diagrams for `UI`, `InputHandler` and `EphemeralDb` may be denoted as just an interface in the UI component diagram but perhaps consider changing their colour so that it is easier to follow from the previous higher level architectural diagram?

<img width="219" alt="screen shot 2016-10-25 at 5 08 49 pm" src="https://cloud.githubusercontent.com/assets/2897395/19679761/bc6f62c8-9ad5-11e6-8296-1a9fdd4787cf.png">
- Update all the component diagrams for `Controller`, `Storage`, `Model`, etc. I noticed that the diagrams still contain information from the previous `addressbook-level4` project.
- I don't think the arrows should be greyed out for the Parent-Child relationship. Perhaps find a way to reorganise the all the connections?

<img width="797" alt="screen shot 2016-10-25 at 5 02 13 pm" src="https://cloud.githubusercontent.com/assets/2897395/19680051/bd1e50ac-9ad6-11e6-848b-67f8af5ab96e.png">
# User Guide
- Some numbering format issue here

<img width="945" alt="screen shot 2016-10-25 at 11 46 01 am" src="https://cloud.githubusercontent.com/assets/2897395/19679229/9de381ba-9ad3-11e6-8f76-18545ab3b5e9.png">
- The statement "Use case ends" should be on a new line

<img width="793" alt="screen shot 2016-10-25 at 11 46 40 am" src="https://cloud.githubusercontent.com/assets/2897395/19679273/bee89210-9ad3-11e6-9132-4161e9e10425.png">
# Architecture review

I quite surprised with your team's approach in designing the architecture of your app. I know the patterns found in react.js and other similar frameworks has been well received and adopted in the recent years among the web and mobile community. It's interesting to see the concept being applied in desktop applications. I think the overall structure is good to go. What's your thoughts on this, Prof @damithc?

**Comment by ysqty** [comment]
Also, my apologies for taking this long to review.

**Comment by damithc** [comment]
No additional comments on the part that is up-to-date. Good job on explaining things clearly :+1: . The outdated parts need to be updated before I can comment on those.

**Comment by ysqty** [comment]
@Candiie fyi
