### ISSUE TITLE
Buggy TodoListDB methods

### ISSUE THREAD

**Issue by louietyj** [CS2103AUG2016-F11-C1/main#146]
* Forget to call save() when they should
* Call save() multiple times in intermediate steps for an atomic transaction and end up breaking undo/redo
* Plagiarized code documentation doesn't match actual implementation

**Comment by ChaseTiong** [comment]
All the old methods are been removed in the Tag Functionality PR. I changed it to only 1 method so save() will only be called once. 
And may I ask which part of the code did i Plagiarized?

**Comment by louietyj** [comment]
Yes, as we have mentioned to you many times, your PR #135 cannot be merged because it is so monstrously huge that no one can verify its correctness. Either you break it into manageable PRs that people can actually read, or you maintain your own fork of this repo. Please go and learn proper Git workflow.

**Comment by ChaseTiong** [comment]
I am not asking you guys to merge that PR (#135) anymore. But #142 , so I can remove the the mess i created in ToDoList db methods.

**Comment by louietyj** [comment]
I apologize for the previous title. Not enough sleep.
