### ISSUE TITLE
Write IndexView interface (controller)

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#15]
Need to outline the **interface for passing properties** that a controller can access to load and render a View. (see #3 for interface for a View to render another View).

Current suggested interface for **IndexView**:

``` java
List<Task> tasks;   // Might or might not be a proper subset of all tasks
List<Tag> tags;     // All tags
String consoleOutput;

// Total numbers for tasks (numCompleteTasks + numIncompleteTasks = numTotalTasks)
int numCompleteTasks;
int numIncompleteTasks;
int numOverdueTasks;

// Total numbers for events (should add up to total number of events)
int numCurrentEvents;
int numPastEvents;

// More?
```

Will have more interfaces for other (future) Views.

**Comment by louietyj** [comment]
Closed, #3 provides latest "view API"

**Comment by irvinlim** [comment]
Actually they're different APIs, this is particularly for IndexView. Because I want to display the number of complete tasks etc. in the sidebar, so I need those numbers. Just KIV first.

**Comment by louietyj** [comment]
Oops, my bad

**Comment by irvinlim** [comment]
Can close as of #85
