### ISSUE TITLE
Handle invalid command

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#16]
Right now it crashes on invalid command entered.

We take it that a command is invalid if and only if confidence returned from all controllers <= 0.

**Comment by louietyj** [comment]
I don't think confidence is meant to describe an invalid command. An invalid command could be something that is only caught later, like `destroy 5` when 5 does not exist.

I'll think about a consistent way to handle user errors.

**Comment by irvinlim** [comment]
That might be a different thing, but being able to catch the error when no controller is able to handle it should be done at the UI level, since it's not appropriate to call `.process()` on any arbitrary controller. I'll also expose an interface to indicate errors on the console, rather than just normal text, to handle this type of invalid commands.

Perhaps we can make a distinction between them as such:
- **Incorrect**: The command cannot be parsed by any controller.
- **Invalid**: The command returned an error (?) by the controller.

**Comment by louietyj** [comment]
Ok, then we need to change the workflow. Right now `.process()` is the one that actually parses the whole command into what it needs to do. We need `.inputConfidence()` to do that right from the start.
