### ISSUE TITLE
View with Dates

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#17]
Issue with viewing of confusion of current week and next week
The current display Tuesday may refer to this week or next Tuesday. 
Hence, we should implement the display the day the actual date. Moreover, including Tomorrow for a day difference instead of just display as the day.

**Comment by irvinlim** [comment]
@ChaseYaoCong Should be more specific with the problem and the suggested solution in the comments and title, eg. Might be problematic to differentiate between dates for this and next week, like how "Tuesday" could either mean this Tuesday or next Tuesday.

**Comment by ChaseTiong** [comment]
Noted. Description edited

**Comment by irvinlim** [comment]
Fixed with #21
