### ISSUE TITLE
Add help text for every command

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#24]
We need to add support for the `help` command, which means that every controller/command needs to provide strings for **command name**, **description** and **syntax**.

On an incorrect command (e.g. `delete 5` when there are less than 5 items in the list), the controller should also pass the correct syntax to the console via the interfaced property `view.consoleOutput` (to be implemented as well).

This should be done through a `HelpView`.

**Comment by ChaseTiong** [comment]
We are required to add success message too! To pass to consoleOutput when it is a valid command
