### ISSUE TITLE
Invalid command - feedback

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#35]
When invalid command, we should re-direct user to view all the help command. 

Have to change the style of command input. (There is a bug with the style)
Sometime, the "red" style will not be remove even though correct command is been inserted.

**Comment by irvinlim** [comment]
Don't think we should open a different view, rather, the Controller has to return a String with the error message on an error.

We don't need to render a new View when there's an error, just at `inputConfidence` or `process`. It should return the two types of errors we earlier talked about (incorrect vs invalid command).

**Comment by irvinlim** [comment]
Cancel last.

We should store the currentView in `UiManager`, and create a `UiManager.showConsoleMessage(String message)` method, which sets the `consoleMessage` property and re-renders the view.
