### ISSUE TITLE
Pass in total numbers into IndexView

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#36]
To be displayed in the sidebar.

**Comment by louietyj** [comment]
- Incomplete Tasks - `db.countIncompleteTasks() -> int`
  - Overdue Tasks - `db.countOverdueTasks() -> int`
- Events in future - `db.countFutureEvents() -> int`

**TODO:**
- [x] Model count methods (@louietyj) - #84
- [x] View statistics (@irvinlim) - #85
