### ISSUE TITLE
Issue with view after delete command. 

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#57]
![image](https://cloud.githubusercontent.com/assets/16850418/19411413/c7885f88-9333-11e6-8ebe-a0d380818614.png)

I think our view had to be bigger to cater for more than 1 line of output.

**Comment by irvinlim** [comment]
The problem is actually the number of items on the screen. Trivial fix, will fix later.

**Comment by irvinlim** [comment]
Fixed with e0566a8.
