### ISSUE TITLE
Issue with inserting of event into db

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#59]
Currently, we are inserting the parsing wrongly for event. 

We also have to decide `add event test by tmr` , are we inserting it as from today to tmr? or how are we inserting it?

`add event test from tmr to wed` , this is going to be insert into db as from wed to null.
The result should be inserting into db from tmr to wed instead.

**Comment by louietyj** [comment]
`add event test by tmr` is as expected. One timing => take it as startdate with null enddate.
