### ISSUE TITLE
Modify config command to allow user to change theme

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#63]
We should preset a few color theme for user to change if they like under config command.

When user enter `config`, some e.g. of how config can be used (change name and database) and a few theme should be listed out. 

For e.g user should enter 
`config` or `config theme 1` (if they already know the command)

**Comment by irvinlim** [comment]
This should be a low priority, not sure how useful changing the theme is (plus need to write a whole bunch of css again)

**Comment by louietyj** [comment]
I'm closing this issue, it's a nice-to-have but honestly adds no real value to our project and would probably take up quite a lot of time on the CSS side.

**Comment by ChaseTiong** [comment]
I not sure if you guys want to leave it open. Is for `milestone planning` for our next week that's why i put v0.4. If you guys dont want it, can just close it again. :)

**Comment by louietyj** [comment]
As mentioned, adds no real value to our project. We have a shit ton of other unimplemented stuff that is more important.
