### ISSUE TITLE
Alias command

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#64]
Modify the database and make alias controller.

This will allow `advanced user` to change command as they like.

`alias add a`
`a task cs2103 by today` --> this should be equivalent to add.

---
- [x] Add alias, Alias view (#99)
- [x] Unalias (#131)
- [x] Use alias (#123)

**Comment by ChaseTiong** [comment]
Duplicate issues with #99

**Comment by irvinlim** [comment]
Actually, the aliasing is not yet complete, so shouldn't close right

**Comment by ChaseTiong** [comment]
opps, i thought i saw a duplicated issues. ><
