### ISSUE TITLE
removeTag command

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#66]
This command should remove the existence of the tag.

For e.g. `removeTag cs2103`, it will look through the whole database to find all task that have the tag `cs2103` and replace with `null`.

**Comment by irvinlim** [comment]
Oops, sorry click wrong

**Comment by irvinlim** [comment]
This functionality is pretty useless actually, and if we are implementing `delete tag` this functionality is a proper subset of that. Closing this, reopen if you disagree.
