### ISSUE TITLE
Load previous command(s) in console

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#68]
Similar to a terminal on an OS, the user should be able to access the history of previous commands by pressing `Up` and `Down` in the console.

**Comment by louietyj** [comment]
Does jfx allow you to access keyboard input directly? Else you may have a problem (:

**Comment by ChaseTiong** [comment]
I saw my friend is able to create shortcut from fxml. I think is a good idea. :)
