### ISSUE TITLE
Delete tag from TagList

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#69]
If possible. Search through by name or tag and display if more than 1 is found to ask user to choose by index.

`delete name cs2103`
`delete tag project`

**Comment by irvinlim** [comment]
Don't think we should allow references to items by name. It's not expected behaviour.

`delete tag` conflicts with `removeTag` though. We should rename `removeTag` to something like `untag` or something.

**Comment by ChaseTiong** [comment]
@irvinlim are we still doing this? I agree with you that it is not expected behaviour. 

Should just let user to untag from the task to the point where the tag does not exist anymore.
Reopen if you want to continue on with this feature
