### ISSUE TITLE
Natty parse some date format wrongly

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#93]
Natty parse date format '28/10/16' as `20:00` (Today 8pm)

If time persists, we should fix this.

**Comment by louietyj** [comment]
Unlikely that we can fix this. Natty is a black-box abstraction. Natty expects mm/dd/yyyy.

Please don't add issues to milestones when we are not even sure the issue is fixable.

**Comment by louietyj** [comment]
You can re-open this if you figure out a way to customize Natty's date parser, short of forking the code.
